name: webview_useragent_example
description: "Demonstrates how to use the webview_useragent plugin."
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  webview_useragent:
    path: ../
  webview_useragent_platform_interface:
    path: ../../webview_useragent_platform_interface

  cupertino_icons: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
