name: webview_useragent
description: "A Flutter plugin to get native WebView UserAgent."
repository: https://github.com/strysk/webview_useragent/tree/main/webview_useragent
version: 1.0.0

environment:
  sdk: '^3.3.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  webview_useragent_ios: ^1.0.0
  webview_useragent_android: ^1.0.0
  webview_useragent_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: webview_useragent_android
      ios:
        default_package: webview_useragent_ios
